### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by kcgthb** [OSC/mod_ood_proxy#15]
Hi!

Not sure if it's the best place to ask, but the [docs](https://osc.github.io/ood-documentation/master/infrastructure/mod-ood-proxy/handlers/analytics-handler.html) say:
> Please contact us if you’d like to enable this feature and have access to it. This will require us to generate a new Property ID for your center that we can then share with you.

So here I am :)

I guess I can generate my own Property ID and use it in the `analytics:` section of `ood_portal.yml` but is it the only thing to do? Or do I need some metric mapping on the GA side too?

Thanks!

**Comment by nickjer** [comment]
Ah, you are the first to notice that and ask, so that means you will have to bear with my first attempt at a response to this.

Since OnDemand 1.3 we now offer two methods for gathering metrics. The first method as you noticed is through Google Analytics and the latter is the data we log under:

```
/var/log/httpd24/<host>_error_ssl.log
```

which is logged in a `<key>="<value>"` format. We are *hoping* to develop tools in the future to parse these logs and generate reports, but not quite there yet.

Google Analytics has pros:

- provides geolocation from ip address
- converts user agent to browser and OS for you
- we have internal tool that generates reports for us using the Google Analytics API that we can share

and some cons:

- can only request a max of 7 dimensions from API (requires you to download multiple datasets and combine them)
- can only get 10,000 records per API request (need to loop until captured all the data)
- kind of wonky when determining a "session", so I redefine what a session is in the internal tool we use for metrics reporting

Note that the log output I mentioned above contains all of the same data that we feed to Google Analytics, but it is unprocessed (so you'd be responsible for geolocation and parsing user agents).

If you would like to use Google Analytics you have two options:

1. We host the analytics for you from our GA account and grant you admin access to the relevant property. We would setup all the custom dimensions and "Authenticated Users" view. This is the simplest solution but not sure of the privacy concerns your data center would have as OSC would have access to raw data (see below for what is recorded).

2. You would setup and manage your own GA account. You would need to create a property with the given custom dimensions/metrics (exactly as they are defined below):

   ![image](https://user-images.githubusercontent.com/4260509/39820183-3cd02e14-5373-11e8-9181-3980b7b1fdcf.png)

   ![image](https://user-images.githubusercontent.com/4260509/39820488-e997ede4-5373-11e8-9970-8e8ebc58d90b.png)

   The relevant code that records the values for those dimensions from OnDemand can be found at: https://github.com/OSC/mod_ood_proxy/blob/c3769fa727ad953c764fa705c258b6eddcede04b/lib/analytics.lua#L46-L55

   You may also want to setup an "Authenticated Users" view as well.

**Comment by kcgthb** [comment]
Thanks for the thorough explanation, much appreciated.

We'll certainly go ahead with our own "property", as we're already tracking usage for a bunch of our other services in GA.

**Comment by nickjer** [comment]
Great, feel free to open up any issues that you may uncover with Google Analytics.
